var password;
var pass1="nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthao=mguyentantu ";
var pass2="nguyenquangmenhoangnhankhoi ";
var pass3="Ami Ishihara";
var pass5="Hara Chihiro (Leila Aizaki)";
var pass6="Jun Aizawa";
var pass7="Tsuna Kimura";
var pass8="Yui Nishikawa";
var pass9="Yumi Maeda";
password=prompt('Đây là khu vực giành riêng cho BQT. Vui lòng truy cập vào trang https://anhjavdep.blogspot.com/ để tìm phim!','');
if (password==pass1 || password==pass2 || password==pass3 || password==pass5 || password==pass6 || password==pass7 || password==pass8 || password==pass9)
alert('Mật khẩu sai! Bấm Ok để chúng tôi đưa bạn về trang https://anhjavdep.blogspot.com/');
else
{
window.location="https://anhjavdep.blogspot.com/";
}
