var nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5;
var nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q51="nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthao=mguyentantu nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthao=mguyentantu ";
nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5=prompt('Đây là khu vực giành riêng cho BQT. Vui lòng truy cập vào trang https://anhjavdep.blogspot.com/ để tìm phim! (Hoặc bấm Oke để chung tôi đưa bạn về trang https://anhjavdep.blogspot.com/ một cách nhanh nhất)','');
if (nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5==nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q51)
alert('Mật khẩu đúng! Nếu bạn không thuộc bộ phận BQT thì việc truy cập này là trái với qui định của trang, vui lòng truy cập vào trang https://anhjavdep.blogspot.com/. Không nên cố gắng truy cập vào trang chủ hay các trang khác của https://sexjavhay.blogspot.com/!');
else
{
window.location="https://anhjavdep.blogspot.com/";
}
