var nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu;
var nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu1="nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu0--- nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu";
nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu=prompt('Đây là khu vực giành riêng cho BQT. Vui lòng truy cập vào trang https://anhjavdep.blogspot.com/ để tìm phim!','');
if (nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu==nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthaomguyentantu1)
alert('Mật khẩu sai! Bấm Ok để chúng tôi đưa bạn về trang https://anhjavdep.blogspot.com/');
else
{
window.location="https://anhjavdep.blogspot.com/";
}
