var nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5;
var nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q51="nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthao=mguyentantu nguyenquangmenhoangnhankhoi m1t2t3c4q5 _+_ nguyenthihongcuong_nguyenthihongthao=mguyentantu ";
nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5=prompt('Đây là khu vực giành riêng cho BQT. Vui lòng truy cập vào trang https://anhjavdep.blogspot.com/ để tìm phim!','');
if (nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q5==nguyenquangmenhoangnhankhoinguyenquangmenhoangnhankhoi_m1t2t3c4q51)
alert('Mật khẩu sai! Bấm Ok để chúng tôi đưa bạn về trang https://anhjavdep.blogspot.com/');
else
{
window.location="https://anhjavdep.blogspot.com/";
}
